# flatcat config (TOML)
    
root = "."
output = "flatcat.md"
include_tree = true
tree_depth = 0
respect_gitignore = true
ignore_extensions = [
    # Images
    ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".svg", ".webp", ".avif",
    # Videos  
    ".mp4", ".avi", ".mov", ".wmv", ".flv", ".webm", ".mkv",
    # Audio
    ".mp3", ".wav", ".flac", ".aac", ".ogg", ".m4a",
    # Archives
    ".zip", ".rar", ".7z", ".tar", ".gz", ".bz2", ".xz",
    # Executables
    ".exe", ".dll", ".so", ".dylib", ".app", ".deb", ".rpm", ".msi",
    # Documents (binary)
    ".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx",
    # Fonts
    ".ttf", ".otf", ".woff", ".woff2", ".eot",
    # Other binary/large files
    ".bin", ".dat", ".db", ".sqlite", ".sqlite3", ".pem", ".key", ".crt", ".p12",
    # Compiled/generated files
    ".pyc", ".pyo", ".class", ".o", ".obj", ".lib", ".a"
]

[filters]
include = []    # e.g. ["src/**", "*.py"], if non-empty, only these matchers are included
exclude = [
    # Version control
    ".git/**", ".git", ".svn/**", ".svn", ".hg/**", ".hg",
    
    # Python
    "**/__pycache__/**", "__pycache__", 
    "venv/**", "venv", ".venv/**", ".venv", "env/**", "env", ".env/**",
    "*.egg-info/**", "*.egg-info",
    ".pytest_cache/**", ".pytest_cache", ".mypy_cache/**", ".mypy_cache",
    ".tox/**", ".tox", ".coverage", "htmlcov/**", "htmlcov",
    
    # Node.js / JavaScript
    "node_modules/**", "node_modules",
    ".next/**", ".next", ".nuxt/**", ".nuxt", 
    "out/**", "out", "dist/**", "dist", "build/**", "build",
    ".turbo/**", ".turbo", ".vercel/**", ".vercel", ".netlify/**", ".netlify",
    "coverage/**", "coverage", ".nyc_output/**", ".nyc_output",
    
    # Lock files (usually too large and not useful for LLMs)
    "package-lock.json", "pnpm-lock.yaml", "yarn.lock", "bun.lockb",
    "Pipfile.lock", "poetry.lock", "Cargo.lock",
    
    # Cache and temporary
    ".cache/**", ".cache", ".tmp/**", ".tmp", "tmp/**", "tmp",
    ".DS_Store", "Thumbs.db", "*.log",
    
    # IDE and editor
    ".vscode/**", ".vscode", ".idea/**", ".idea",
    "*.swp", "*.swo", "*~",
    
    # Build artifacts
    "target/**", "target", # Rust
    "bin/**", "obj/**", # .NET
    "*.min.js", "*.min.css", # Minified files
    
    # Large data files
    "*.csv", "*.tsv", "*.json.gz", "*.xml.gz"
]

[format]
heading = "### {path}"
fence_language_from_extension = true
preamble = """
This file was generated by flatcat.

It contains a tree view of {root} and the full text of non-ignored files.
Directories marked with * are ignored; their contents are not listed.
"""